# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=10)),
            ],
        ),
    ]
